# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-147085505-1'

menu:
## - {name: 'おすすめ', folder: 'pages', file: 'facts.html'}
- {name: 'NEWS', folder: 'pages', file: 'news.html'}
## - {name: 'たまご', folder: 'pages', file: 'sample-posts.html'}
- {name: 'このサイトについて', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
## - {icon: 'twitter', link: 'https://twitter.com/paululele'}
## - {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
## - {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'envelope', link: 'rm.o.s.h.m.k.u.f.a@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: '次へ'
  previous_page: '前へ'

sharing_button_prompt: 'シェアしてね！'

related_posts: '関連記事'

post_date_prefix: '投稿日：'
